






upload: FORCE
	pio run -t upload -e esp


nano: FORCE
	pio run -t upload -e nano


esp: FORCE
	pio run -t upload -e esp



esp32: FORCE
	pio run -t upload -e esp32

mega: FORCE
	pio run -t upload -e mega


serial: FORCE
	pio device monitor -b 115200


FORCE: ;
